### PR TITLE
Updated Nav Bar Component 

### PR DESCRIPTION
**Pull request by Amrikghosh20000**
Nav Bar component is aligned but responsive Hemberger icon <<Functionality issue>>

### CODE REVIEW

**Comment by XCoder-Ayush** [comment]
Add Prettier support in the codebase to remain consistent in the nonfunctional coding style.

**Comment by Amrikghosh20000** [comment]
Prettier added and code is formatted with the latest code <<Card>> and <<Box Component >>.

**Comment by XCoder-Ayush** [comment]
There are many design errors in the code.
1) Don't directly hardcode HTML. It is the worst thing you can do.
2) Assume that you are calling rest API from service and receiving the data. So get the data in objects in services and manage state to different components.(so since now backend service data is not available, hardcode the data in the service.)
3) Use Shadcn. 
4) Assume proper components are made to make the code reusable, manageable and extensible.
5) For state management, if needed -> Use Redux

**Comment by XCoder-Ayush** [comment]
Some fixes to be done.

1. Folder and comp name should be consistent.(like Jumpotron and Slider are inconsistent. another one is in the Footer)
basically, all 3 names should be the same - The folder, The file, and the function name

2. All static assets like videos, images and gifs etc should be present inside the assets folder only.

3. Generic naming like CardContainer should strictly not be used. Since it is signifying Blog here, so instead name it as Blog
container.

4. Don't just keep making component and services altogether, please try to write reusable code. I think there's no point of overview service. If you want that to be there, you need to justify a proper reason.

**Comment by Amrikghosh20000** [comment]
1-Noted about the file , folder and function naming conversation need to follow while developing the solutions.  
2-That video path was creating some issues related to "src" in video tag . For that reason I kept inside the component for alignment of the website as of now it will updated.
3.Noted same as point `1`.
4.As per the UX UI design there must be 3 cards which will tell about some elaborative blog posts and details and the above card will only focus on some particular blog posts or data . So it done based on the design aspects, but in future components will be reused to optimized the overall solution. And for the "overview.service.js" created for practice purpose and also for dynamic data shall be needed in upcoming days.

**Comment by XCoder-Ayush** [comment]
Okay. everything is fine according to the issues mentioned in the meeting.

**Pull request merged**
